name: "auth_hf"
dependencies: 
  angel_auth: "^1.1.0-alpha"
  angel_configuration: "^1.1.0-alpha"
  angel_framework: "^1.1.0-alpha"
  angel_jael: "^1.0.0-alpha"
  angel_model: "^1.0.0"
  angel_mongo: "^1.0.0"
  angel_relations: ^1.0.0
  angel_serialize: "^1.0.0-alpha"
  angel_static: "^1.3.0-alpha"
  angel_validate: "^1.0.0"
  angel_oauth2: 
    git: "https://github.com/angel-dart/oauth2.git"
  html: ^0.13.2
  mailer: ^1.1.0
  pointycastle: ^0.10.0
dev_dependencies:
  angel_auth_oauth2: ^1.0.0
  angel_serialize_generator: "^1.0.0-alpha"
  angel_test: ^1.1.0-alpha
  build_runner: "^0.5.0"
  oauth2: ^1.1.0
  test: ^0.12.0