base_url: http://localhost:3000
mongo_db: $MONGO_DB
jwt_secret: $JWT_SECRET
mail:
  secure: $MAIL_SECURE
  host: $MAIL_HOST
  port: $MAIL_PORT
  from: $MAIL_FROM
  username: $MAIL_USERNAME
  password: $MAIL_PASSWORD